name: Build CI
on:
  push:
    branches:
      - master
      - '*.x'

  pull_request:
    branches: 
      - master
      - '*.x'

concurrency: 
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read
  pull-requests: read


jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Generate prisma client
        run: npx prisma generate
        working-directory: ./packages/prisma
      - name: Run Build
        run: npm run build